name: 'Continuous Integration'

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-test.txt
          pip install "anyio>=3.0,<4" requests

      - name: Run model tests
        run: |
          mkdir -p reports
          pytest --cov-config=.coveragerc --cov-report term --cov-report xml:reports/coverage.xml --junitxml=reports/junit.xml --cov=challenge tests/model

      - name: Run API tests
        run: |
          pytest --cov-config=.coveragerc --cov-report term --cov-report xml:reports/coverage.xml --junitxml=reports/junit.xml --cov=challenge tests/api
